// <auto-generated />
using Amazon.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amazon.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240728175955_ProductTable")]
    partial class ProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amazon.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Electronics",
                            Description = "High performance laptop with 16GB RAM and 512GB SSD.<br/> Ideal for gaming, programming, and design.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Laptop",
                            Price = 1000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Electronics",
                            Description = "Latest smartphone with 5G connectivity and 128GB storage.<br/> Features a stunning display and excellent camera.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Smartphone",
                            Price = 699.99000000000001
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Wearables",
                            Description = "Smartwatch with heart rate monitor and GPS tracking.<br/> Perfect for fitness enthusiasts and tech lovers.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Smartwatch",
                            Price = 199.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Electronics",
                            Description = "Versatile tablet with 10.5-inch display and 64GB storage.<br/> Great for entertainment and productivity on the go.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Tablet",
                            Price = 329.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
